# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{coupler}
  s.version = "0.0.0"
  s.platform = %q{java}

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jeremy Stephens"]
  s.date = %q{2010-01-26}
  s.default_executable = %q{coupler}
  s.description = %q{Coupler is an application based on Sinatra and JRuby for linking data}
  s.email = %q{jeremy.f.stephens@vanderbilt.edu}
  s.executables = ["coupler"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc",
     "TODO"
  ]
  s.files = [
    ".document",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "TODO",
     "VERSION",
     "bin/coupler",
     "coupler.gemspec",
     "features/matchers.feature",
     "features/projects.feature",
     "features/resources.feature",
     "features/scenarios.feature",
     "features/step_definitions/coupler_steps.rb",
     "features/step_definitions/transformations_steps.rb",
     "features/support/env.rb",
     "features/transformations.feature",
     "lib/coupler.rb",
     "lib/coupler/base.rb",
     "lib/coupler/comparators.rb",
     "lib/coupler/comparators/base.rb",
     "lib/coupler/comparators/exact.rb",
     "lib/coupler/config.rb",
     "lib/coupler/database.rb",
     "lib/coupler/extensions.rb",
     "lib/coupler/extensions/matchers.rb",
     "lib/coupler/extensions/projects.rb",
     "lib/coupler/extensions/resources.rb",
     "lib/coupler/extensions/scenarios.rb",
     "lib/coupler/extensions/transformations.rb",
     "lib/coupler/helpers.rb",
     "lib/coupler/jobs.rb",
     "lib/coupler/jobs/run_scenario.rb",
     "lib/coupler/jobs/transform.rb",
     "lib/coupler/logger.rb",
     "lib/coupler/models.rb",
     "lib/coupler/models/common_model.rb",
     "lib/coupler/models/matcher.rb",
     "lib/coupler/models/project.rb",
     "lib/coupler/models/resource.rb",
     "lib/coupler/models/scenario.rb",
     "lib/coupler/models/transformation.rb",
     "lib/coupler/scheduler.rb",
     "lib/coupler/score_set.rb",
     "lib/coupler/server.rb",
     "lib/coupler/transformers.rb",
     "lib/coupler/transformers/base.rb",
     "lib/coupler/transformers/downcaser.rb",
     "public/css/960.css",
     "public/css/jquery-ui.css",
     "public/css/reset.css",
     "public/css/style.css",
     "public/css/text.css",
     "public/images/12_col.gif",
     "public/images/16_col.gif",
     "public/images/coupler.png",
     "public/images/home.gif",
     "public/images/sidebar.png",
     "public/images/ui-bg_flat_0_aaaaaa_40x100.png",
     "public/images/ui-bg_flat_75_ffffff_40x100.png",
     "public/images/ui-bg_glass_55_fbf9ee_1x400.png",
     "public/images/ui-bg_glass_65_ffffff_1x400.png",
     "public/images/ui-bg_glass_75_dadada_1x400.png",
     "public/images/ui-bg_glass_75_e6e6e6_1x400.png",
     "public/images/ui-bg_glass_95_fef1ec_1x400.png",
     "public/images/ui-bg_highlight-soft_75_cccccc_1x100.png",
     "public/images/ui-icons_222222_256x240.png",
     "public/images/ui-icons_2e83ff_256x240.png",
     "public/images/ui-icons_454545_256x240.png",
     "public/images/ui-icons_888888_256x240.png",
     "public/images/ui-icons_cd0a0a_256x240.png",
     "public/js/jquery-ui.min.js",
     "public/js/jquery.min.js",
     "public/js/resource.js",
     "script/dbconsole.rb",
     "test.watchr",
     "test/coupler/comparators/test_base.rb",
     "test/coupler/comparators/test_exact.rb",
     "test/coupler/extensions/test_matchers.rb",
     "test/coupler/extensions/test_projects.rb",
     "test/coupler/extensions/test_resources.rb",
     "test/coupler/extensions/test_scenarios.rb",
     "test/coupler/extensions/test_transformations.rb",
     "test/coupler/jobs/test_run_scenario.rb",
     "test/coupler/jobs/test_transform.rb",
     "test/coupler/models/test_matcher.rb",
     "test/coupler/models/test_project.rb",
     "test/coupler/models/test_resource.rb",
     "test/coupler/models/test_scenario.rb",
     "test/coupler/models/test_transformation.rb",
     "test/coupler/test_base.rb",
     "test/coupler/test_comparators.rb",
     "test/coupler/test_config.rb",
     "test/coupler/test_database.rb",
     "test/coupler/test_helpers.rb",
     "test/coupler/test_logger.rb",
     "test/coupler/test_scheduler.rb",
     "test/coupler/test_score_set.rb",
     "test/coupler/test_server.rb",
     "test/coupler/test_transformers.rb",
     "test/coupler/transformers/test_base.rb",
     "test/coupler/transformers/test_downcaser.rb",
     "test/factories.rb",
     "test/helper.rb",
     "test/test_coupler.rb",
     "vendor/mysql-connector-mxj-gpl-5-0-9/COPYING",
     "vendor/mysql-connector-mxj-gpl-5-0-9/README.1st",
     "vendor/mysql-connector-mxj-gpl-5-0-9/lib/aspectjrt.jar",
     "vendor/mysql-connector-mxj-gpl-5-0-9/lib/aspectjtools.jar",
     "vendor/mysql-connector-mxj-gpl-5-0-9/lib/junit.jar",
     "vendor/mysql-connector-mxj-gpl-5-0-9/mysql-connector-mxj-gpl-5-0-9-db-files.jar",
     "vendor/mysql-connector-mxj-gpl-5-0-9/mysql-connector-mxj-gpl-5-0-9.jar",
     "vendor/quartz/lib/VERSIONS.txt",
     "vendor/quartz/lib/core/commons-logging-1.1.jar",
     "vendor/quartz/lib/core/commons-logging-1.1.license",
     "vendor/quartz/lib/core/commons-logging-1.1.notice",
     "vendor/quartz/license.txt",
     "vendor/quartz/quartz-1.6.6.jar",
     "vendor/quartz/readme.txt",
     "vendor/thread_pool/CHANGELOG",
     "vendor/thread_pool/LICENSE",
     "vendor/thread_pool/README",
     "vendor/thread_pool/Rakefile",
     "vendor/thread_pool/lib/thread_pool.rb",
     "vendor/thread_pool/test/test_thread_pool.rb",
     "vendor/thread_pool/thread_pool.gemspec",
     "views/index.erb",
     "views/layout.erb",
     "views/matchers/list.erb",
     "views/matchers/new.erb",
     "views/projects/index.erb",
     "views/projects/new.erb",
     "views/projects/show.erb",
     "views/resources/list.erb",
     "views/resources/new.erb",
     "views/resources/show.erb",
     "views/resources/transform.erb",
     "views/scenarios/list.erb",
     "views/scenarios/new.erb",
     "views/scenarios/run.erb",
     "views/scenarios/show.erb",
     "views/transformations/list.erb",
     "views/transformations/new.erb"
  ]
  s.homepage = %q{http://github.com/coupler/coupler}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Coupler is an application for linking data}
  s.test_files = [
    "test/test_coupler.rb",
     "test/helper.rb",
     "test/factories.rb",
     "test/coupler/test_server.rb",
     "test/coupler/test_database.rb",
     "test/coupler/test_transformers.rb",
     "test/coupler/test_score_set.rb",
     "test/coupler/test_base.rb",
     "test/coupler/test_logger.rb",
     "test/coupler/test_helpers.rb",
     "test/coupler/test_comparators.rb",
     "test/coupler/test_config.rb",
     "test/coupler/test_scheduler.rb",
     "test/coupler/comparators/test_exact.rb",
     "test/coupler/comparators/test_base.rb",
     "test/coupler/models/test_scenario.rb",
     "test/coupler/models/test_resource.rb",
     "test/coupler/models/test_project.rb",
     "test/coupler/models/test_matcher.rb",
     "test/coupler/models/test_transformation.rb",
     "test/coupler/transformers/test_downcaser.rb",
     "test/coupler/transformers/test_base.rb",
     "test/coupler/jobs/test_run_scenario.rb",
     "test/coupler/jobs/test_transform.rb",
     "test/coupler/extensions/test_scenarios.rb",
     "test/coupler/extensions/test_matchers.rb",
     "test/coupler/extensions/test_transformations.rb",
     "test/coupler/extensions/test_projects.rb",
     "test/coupler/extensions/test_resources.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sinatra>, [">= 0"])
      s.add_runtime_dependency(%q<rack-flash>, [">= 0"])
      s.add_runtime_dependency(%q<jdbc-mysql>, [">= 0"])
      s.add_runtime_dependency(%q<sequel>, [">= 0"])
      s.add_development_dependency(%q<mocha>, [">= 0"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
      s.add_development_dependency(%q<activesupport>, [">= 0"])
      s.add_development_dependency(%q<rack-test>, [">= 0"])
      s.add_development_dependency(%q<nokogiri>, [">= 0"])
      s.add_development_dependency(%q<timecop>, [">= 0"])
      s.add_development_dependency(%q<butternut>, [">= 0"])
    else
      s.add_dependency(%q<sinatra>, [">= 0"])
      s.add_dependency(%q<rack-flash>, [">= 0"])
      s.add_dependency(%q<jdbc-mysql>, [">= 0"])
      s.add_dependency(%q<sequel>, [">= 0"])
      s.add_dependency(%q<mocha>, [">= 0"])
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<rack-test>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<timecop>, [">= 0"])
      s.add_dependency(%q<butternut>, [">= 0"])
    end
  else
    s.add_dependency(%q<sinatra>, [">= 0"])
    s.add_dependency(%q<rack-flash>, [">= 0"])
    s.add_dependency(%q<jdbc-mysql>, [">= 0"])
    s.add_dependency(%q<sequel>, [">= 0"])
    s.add_dependency(%q<mocha>, [">= 0"])
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<rack-test>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<timecop>, [">= 0"])
    s.add_dependency(%q<butternut>, [">= 0"])
  end
end

