# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{coupler}
  s.version = "0.0.0"
  s.platform = %q{java}

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jeremy Stephens"]
  s.date = %q{2010-07-14}
  s.default_executable = %q{coupler}
  s.description = %q{Coupler is an application based on Sinatra and JRuby for linking data}
  s.email = %q{jeremy.f.stephens@vanderbilt.edu}
  s.executables = ["coupler"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc",
     "TODO"
  ]
  s.files = [
    ".document",
     "LICENSE",
     "NOTES",
     "README.rdoc",
     "Rakefile",
     "TODO",
     "VERSION",
     "bin/coupler",
     "build.xml",
     "coupler.gemspec",
     "db/migrate/001_initial_schema.rb",
     "db/migrate/002_stub.rb",
     "db/migrate/003_stub.rb",
     "db/migrate/004_create_comparisons.rb",
     "db/migrate/005_move_database_name.rb",
     "db/migrate/006_upgrade_comparisons.rb",
     "db/migrate/007_add_which_to_comparisons.rb",
     "db/migrate/008_add_result_field_to_transformations.rb",
     "db/migrate/009_add_generated_flag_to_fields.rb",
     "db/migrate/010_create_imports.rb",
     "features/connections.feature",
     "features/matchers.feature",
     "features/projects.feature",
     "features/resources.feature",
     "features/scenarios.feature",
     "features/step_definitions/coupler_steps.rb",
     "features/step_definitions/matchers_steps.rb",
     "features/step_definitions/resources_steps.rb",
     "features/step_definitions/scenarios_steps.rb",
     "features/step_definitions/transformations_steps.rb",
     "features/support/env.rb",
     "features/transformations.feature",
     "lib/coupler.rb",
     "lib/coupler/base.rb",
     "lib/coupler/config.rb",
     "lib/coupler/data_uploader.rb",
     "lib/coupler/database.rb",
     "lib/coupler/extensions.rb",
     "lib/coupler/extensions/connections.rb",
     "lib/coupler/extensions/jobs.rb",
     "lib/coupler/extensions/matchers.rb",
     "lib/coupler/extensions/projects.rb",
     "lib/coupler/extensions/resources.rb",
     "lib/coupler/extensions/results.rb",
     "lib/coupler/extensions/scenarios.rb",
     "lib/coupler/extensions/transformations.rb",
     "lib/coupler/extensions/transformers.rb",
     "lib/coupler/helpers.rb",
     "lib/coupler/jobs.rb",
     "lib/coupler/jobs/run_scenario.rb",
     "lib/coupler/jobs/transform.rb",
     "lib/coupler/logger.rb",
     "lib/coupler/models.rb",
     "lib/coupler/models/common_model.rb",
     "lib/coupler/models/comparison.rb",
     "lib/coupler/models/connection.rb",
     "lib/coupler/models/field.rb",
     "lib/coupler/models/import.rb",
     "lib/coupler/models/job.rb",
     "lib/coupler/models/jobify.rb",
     "lib/coupler/models/matcher.rb",
     "lib/coupler/models/project.rb",
     "lib/coupler/models/resource.rb",
     "lib/coupler/models/resource/runner.rb",
     "lib/coupler/models/result.rb",
     "lib/coupler/models/scenario.rb",
     "lib/coupler/models/scenario/runner.rb",
     "lib/coupler/models/transformation.rb",
     "lib/coupler/models/transformer.rb",
     "lib/coupler/models/transformer/runner.rb",
     "lib/coupler/runner.rb",
     "lib/coupler/scheduler.rb",
     "lib/coupler/scheduler/job_listener.rb",
     "lib/coupler/score_set.rb",
     "lib/coupler/server.rb",
     "misc/README",
     "misc/jruby-json.license",
     "misc/rack-flash.license",
     "script/dbconsole.rb",
     "script/run.rb",
     "src/edu/vanderbilt/coupler/Main.java",
     "tasks/annotations.rake",
     "tasks/db.rake",
     "tasks/environment.rake",
     "tasks/jeweler.rake",
     "tasks/rdoc.rake",
     "tasks/test.rake",
     "tasks/vendor.rake",
     "tasks/web.rake",
     "test.watchr",
     "test/coupler/extensions/test_connections.rb",
     "test/coupler/extensions/test_jobs.rb",
     "test/coupler/extensions/test_matchers.rb",
     "test/coupler/extensions/test_projects.rb",
     "test/coupler/extensions/test_resources.rb",
     "test/coupler/extensions/test_results.rb",
     "test/coupler/extensions/test_scenarios.rb",
     "test/coupler/extensions/test_transformations.rb",
     "test/coupler/extensions/test_transformers.rb",
     "test/coupler/jobs/test_run_scenario.rb",
     "test/coupler/jobs/test_transform.rb",
     "test/coupler/models/scenario/test_runner.rb",
     "test/coupler/models/test_comparison.rb",
     "test/coupler/models/test_connection.rb",
     "test/coupler/models/test_field.rb",
     "test/coupler/models/test_import.rb",
     "test/coupler/models/test_job.rb",
     "test/coupler/models/test_matcher.rb",
     "test/coupler/models/test_project.rb",
     "test/coupler/models/test_resource.rb",
     "test/coupler/models/test_result.rb",
     "test/coupler/models/test_scenario.rb",
     "test/coupler/models/test_transformation.rb",
     "test/coupler/models/test_transformer.rb",
     "test/coupler/scheduler/test_job_listener.rb",
     "test/coupler/test_base.rb",
     "test/coupler/test_config.rb",
     "test/coupler/test_data_uploader.rb",
     "test/coupler/test_database.rb",
     "test/coupler/test_helpers.rb",
     "test/coupler/test_logger.rb",
     "test/coupler/test_models.rb",
     "test/coupler/test_runner.rb",
     "test/coupler/test_scheduler.rb",
     "test/coupler/test_score_set.rb",
     "test/coupler/test_server.rb",
     "test/factories.rb",
     "test/fixtures/people.csv",
     "test/helper.rb",
     "test/test_coupler.rb",
     "vendor/ruby/thread_pool/CHANGELOG",
     "vendor/ruby/thread_pool/LICENSE",
     "vendor/ruby/thread_pool/README",
     "vendor/ruby/thread_pool/Rakefile",
     "vendor/ruby/thread_pool/lib/thread_pool.rb",
     "vendor/ruby/thread_pool/test/test_thread_pool.rb",
     "vendor/ruby/thread_pool/thread_pool.gemspec",
     "webroot/public/css/960.css",
     "webroot/public/css/dataTables.css",
     "webroot/public/css/jquery-ui.css",
     "webroot/public/css/jquery.treeview.css",
     "webroot/public/css/reset.css",
     "webroot/public/css/style.css",
     "webroot/public/css/text.css",
     "webroot/public/favicon.ico",
     "webroot/public/images/12_col.gif",
     "webroot/public/images/16_col.gif",
     "webroot/public/images/add.png",
     "webroot/public/images/ajax-loader.gif",
     "webroot/public/images/cog.png",
     "webroot/public/images/coupler.png",
     "webroot/public/images/hammer.png",
     "webroot/public/images/home.gif",
     "webroot/public/images/jobs.gif",
     "webroot/public/images/sidebar-bottom.png",
     "webroot/public/images/sidebar.png",
     "webroot/public/images/treeview-default-line.gif",
     "webroot/public/images/treeview-default.gif",
     "webroot/public/images/ui-anim_basic_16x16.gif",
     "webroot/public/images/ui-bg_flat_0_aaaaaa_40x100.png",
     "webroot/public/images/ui-bg_flat_75_ffffff_40x100.png",
     "webroot/public/images/ui-bg_glass_55_fbf9ee_1x400.png",
     "webroot/public/images/ui-bg_glass_65_ffffff_1x400.png",
     "webroot/public/images/ui-bg_glass_75_dadada_1x400.png",
     "webroot/public/images/ui-bg_glass_75_e6e6e6_1x400.png",
     "webroot/public/images/ui-bg_glass_95_fef1ec_1x400.png",
     "webroot/public/images/ui-bg_highlight-soft_75_cccccc_1x100.png",
     "webroot/public/images/ui-icons_222222_256x240.png",
     "webroot/public/images/ui-icons_2e83ff_256x240.png",
     "webroot/public/images/ui-icons_454545_256x240.png",
     "webroot/public/images/ui-icons_888888_256x240.png",
     "webroot/public/images/ui-icons_cd0a0a_256x240.png",
     "webroot/public/js/ajaxupload.js",
     "webroot/public/js/jquery-ui.min.js",
     "webroot/public/js/jquery.dataTables.min.js",
     "webroot/public/js/jquery.min.js",
     "webroot/public/js/jquery.timeago.js",
     "webroot/public/js/jquery.tooltip.min.js",
     "webroot/public/js/jquery.treeview.min.js",
     "webroot/public/js/resource.js",
     "webroot/views/connections/index.erb",
     "webroot/views/connections/list.erb",
     "webroot/views/connections/new.erb",
     "webroot/views/connections/show.erb",
     "webroot/views/index.erb",
     "webroot/views/jobs/index.erb",
     "webroot/views/jobs/list.erb",
     "webroot/views/layout.erb",
     "webroot/views/matchers/form.erb",
     "webroot/views/matchers/list.erb",
     "webroot/views/projects/form.erb",
     "webroot/views/projects/index.erb",
     "webroot/views/projects/show.erb",
     "webroot/views/resources/edit.erb",
     "webroot/views/resources/index.erb",
     "webroot/views/resources/list.erb",
     "webroot/views/resources/new.erb",
     "webroot/views/resources/show.erb",
     "webroot/views/resources/transform.erb",
     "webroot/views/results/index.erb",
     "webroot/views/results/show.erb",
     "webroot/views/scenarios/index.erb",
     "webroot/views/scenarios/list.erb",
     "webroot/views/scenarios/new.erb",
     "webroot/views/scenarios/run.erb",
     "webroot/views/scenarios/show.erb",
     "webroot/views/sidebar.erb",
     "webroot/views/transformations/for.erb",
     "webroot/views/transformations/index.erb",
     "webroot/views/transformations/list.erb",
     "webroot/views/transformations/new.erb",
     "webroot/views/transformers/edit.erb",
     "webroot/views/transformers/form.erb",
     "webroot/views/transformers/index.erb",
     "webroot/views/transformers/list.erb",
     "webroot/views/transformers/new.erb",
     "webroot/views/transformers/preview.erb"
  ]
  s.homepage = %q{http://github.com/coupler/coupler}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Coupler is an application for linking data}
  s.test_files = [
    "test/test_coupler.rb",
     "test/helper.rb",
     "test/factories.rb",
     "test/coupler/test_server.rb",
     "test/coupler/test_runner.rb",
     "test/coupler/test_data_uploader.rb",
     "test/coupler/test_database.rb",
     "test/coupler/test_score_set.rb",
     "test/coupler/test_base.rb",
     "test/coupler/test_logger.rb",
     "test/coupler/test_helpers.rb",
     "test/coupler/test_models.rb",
     "test/coupler/test_config.rb",
     "test/coupler/test_scheduler.rb",
     "test/coupler/scheduler/test_job_listener.rb",
     "test/coupler/models/test_import.rb",
     "test/coupler/models/test_transformer.rb",
     "test/coupler/models/test_scenario.rb",
     "test/coupler/models/test_job.rb",
     "test/coupler/models/test_resource.rb",
     "test/coupler/models/test_comparison.rb",
     "test/coupler/models/test_result.rb",
     "test/coupler/models/test_field.rb",
     "test/coupler/models/test_project.rb",
     "test/coupler/models/test_matcher.rb",
     "test/coupler/models/test_connection.rb",
     "test/coupler/models/test_transformation.rb",
     "test/coupler/models/scenario/test_runner.rb",
     "test/coupler/jobs/test_run_scenario.rb",
     "test/coupler/jobs/test_transform.rb",
     "test/coupler/extensions/test_scenarios.rb",
     "test/coupler/extensions/test_imports.rb",
     "test/coupler/extensions/test_jobs.rb",
     "test/coupler/extensions/test_results.rb",
     "test/coupler/extensions/test_matchers.rb",
     "test/coupler/extensions/test_transformers.rb",
     "test/coupler/extensions/test_connections.rb",
     "test/coupler/extensions/test_transformations.rb",
     "test/coupler/extensions/test_projects.rb",
     "test/coupler/extensions/test_resources.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sinatra>, [">= 0"])
      s.add_runtime_dependency(%q<rack-flash>, [">= 0"])
      s.add_runtime_dependency(%q<jdbc-mysql>, [">= 0"])
      s.add_runtime_dependency(%q<sequel>, [">= 0"])
      s.add_development_dependency(%q<mocha>, [">= 0"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
      s.add_development_dependency(%q<rack-test>, [">= 0"])
      s.add_development_dependency(%q<nokogiri>, [">= 0"])
      s.add_development_dependency(%q<timecop>, [">= 0"])
      s.add_development_dependency(%q<forgery>, [">= 0"])
      s.add_development_dependency(%q<factory_girl>, [">= 0"])
    else
      s.add_dependency(%q<sinatra>, [">= 0"])
      s.add_dependency(%q<rack-flash>, [">= 0"])
      s.add_dependency(%q<jdbc-mysql>, [">= 0"])
      s.add_dependency(%q<sequel>, [">= 0"])
      s.add_dependency(%q<mocha>, [">= 0"])
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<rack-test>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<timecop>, [">= 0"])
      s.add_dependency(%q<forgery>, [">= 0"])
      s.add_dependency(%q<factory_girl>, [">= 0"])
    end
  else
    s.add_dependency(%q<sinatra>, [">= 0"])
    s.add_dependency(%q<rack-flash>, [">= 0"])
    s.add_dependency(%q<jdbc-mysql>, [">= 0"])
    s.add_dependency(%q<sequel>, [">= 0"])
    s.add_dependency(%q<mocha>, [">= 0"])
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<rack-test>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<timecop>, [">= 0"])
    s.add_dependency(%q<forgery>, [">= 0"])
    s.add_dependency(%q<factory_girl>, [">= 0"])
  end
end

